import { buildMetadata } from "@/lib/metadata";
import LocationPageTemplate from "@/components/LocationPageTemplate";
export const metadata = buildMetadata({ title: "Safety Nets in Indiranagar Bangalore | Nagamani Safety Nets", description: "Safety net installation in Indiranagar, Bangalore. Balcony nets, invisible grills, bird nets. Serving 100 Feet Road, CMH Road and all Indiranagar areas. Call +91 7780613454.", path: "/safety-nets-indiranagar", keywords: ["safety nets indiranagar", "invisible grills indiranagar bangalore", "balcony nets indiranagar"] });
const faqs = [
  { question: "Do you install safety nets in Indiranagar?", answer: "Yes. We serve all of Indiranagar including 100 Feet Road, CMH Road, Old Madras Road, and HAL areas." },
  { question: "How quickly can you install in Indiranagar?", answer: "Same-day installation is available in Indiranagar. Call before noon for same-day service." },
  { question: "Do you install invisible grills in Indiranagar?", answer: "Yes. Invisible grills are very popular in Indiranagar's premium apartments and independent houses. We install SS316 cable grills across all Indiranagar properties." },
  { question: "What safety nets do you recommend for Indiranagar villas?", answer: "For independent villas and houses in Indiranagar, we recommend invisible grills for windows and high-quality balcony nets. We provide a free site inspection to recommend the best option." },
];
export default function IndiranagarPage() {
  return <LocationPageTemplate area="Indiranagar" slug="safety-nets-indiranagar" faqs={faqs} content={<div className="space-y-8"><div><h2>Safety Nets in Indiranagar, Bangalore</h2><p>Indiranagar is one of Bangalore's most upscale residential and commercial neighbourhoods. Known for its tree-lined avenues, premium restaurants, and luxury apartments, Indiranagar residents have high expectations for aesthetics and quality — making invisible grills and premium safety nets the top choice.</p><p>Nagamani Safety Nets has served Indiranagar's discerning residents for over 15 years, providing installation that matches the neighbourhood's premium character.</p></div><div><h2>Safety Net Services in Indiranagar</h2><ul><li><strong>Invisible Grills:</strong> The #1 choice in Indiranagar — SS316 cable grills that are invisible, strong, and maintenance-free.</li><li><strong>Balcony Safety Nets:</strong> Premium nylon and HDPE nets for Indiranagar's modern apartment balconies.</li><li><strong>Bird Nets:</strong> Indiranagar's many mature trees attract birds. Our nets keep them off your balcony.</li><li><strong>Children Safety Nets:</strong> For Indiranagar's family-oriented apartments and villas.</li></ul></div><div><h2>Areas We Cover in Indiranagar</h2><p>100 Feet Road, CMH Road, Old Madras Road, HAL 2nd Stage, HAL 3rd Stage, Domlur, and all adjacent Indiranagar sub-areas.</p></div><div><h2>Premium Service for Premium Residents</h2><p>In Indiranagar, we understand that aesthetics matter as much as functionality. Our clean, professional installation leaves no mess, no visible fittings, and no damage to your property. Call <a href="tel:+917780613454" className="text-green-700 font-semibold">+91 77806 13454</a> for a free inspection today.</p></div></div>} />;
}
