import { buildMetadata } from "@/lib/metadata";
import LocationPageTemplate from "@/components/LocationPageTemplate";
export const metadata = buildMetadata({ title: "Safety Nets in Electronic City Bangalore", description: "Safety net installation in Electronic City, Bangalore. Balcony nets, invisible grills, bird nets for Phase 1 & 2 apartments. Call +91 7780613454.", path: "/safety-nets-electronic-city", keywords: ["safety nets electronic city", "balcony nets electronic city bangalore"] });
const faqs = [
  { question: "Do you serve Electronic City Phase 1 and Phase 2?", answer: "Yes. We serve all of Electronic City including Phase 1, Phase 2, Huskur Road, Neeladri Road, and Bommasandra." },
  { question: "How quickly can you install safety nets in Electronic City?", answer: "Same-day installation is available in Electronic City. Call us before noon for same-day service." },
  { question: "Do you serve IT park apartments near Electronic City?", answer: "Yes. We serve all residential apartments and IT campus accommodations near Electronic City, Infosys campus, and Wipro campus areas." },
  { question: "What is the cheapest safety net option in Electronic City?", answer: "Standard HDPE bird nets start from ₹8/sq ft. Balcony safety nets start from ₹12/sq ft. Call us for a free quote." },
];
export default function ElectronicCityPage() {
  return <LocationPageTemplate area="Electronic City" slug="safety-nets-electronic-city" faqs={faqs} content={<div className="space-y-8"><div><h2>Safety Nets in Electronic City, Bangalore</h2><p>Electronic City is home to thousands of IT professionals and their families, living in modern apartments across Phase 1, Phase 2, and the rapidly developing surrounding areas. Nagamani Safety Nets provides fast, professional safety net installation across all Electronic City areas — including balcony safety nets, invisible grills, bird nets, and cloth hangers.</p></div><div><h2>Why Electronic City Apartments Need Safety Nets</h2><p>Electronic City's apartments are typically high-rise, with open balconies on multiple sides. Many residents have young children or elderly parents. Our safety nets and invisible grills provide peace of mind without compromising the modern aesthetic of your apartment.</p></div><div><h2>Our Services in Electronic City</h2><ul><li>Balcony Safety Nets — from ₹12/sq ft</li><li>Invisible Grills — from ₹150/sq ft</li><li>Bird &amp; Pigeon Nets — from ₹8/sq ft</li><li>Children Safety Nets — from ₹12/sq ft</li><li>Cloth Hangers — from ₹800/unit</li><li>Duct Area Nets — from ₹10/sq ft</li></ul></div><div><h2>Areas Covered in Electronic City</h2><p>We cover all of Electronic City including Phase 1, Phase 2, Huskur Road, Neeladri Road, Bommasandra, Singasandra, Hebbagodi, and adjacent areas.</p></div><div><h2>Contact Us for Electronic City Safety Nets</h2><p>Call <a href="tel:+917780613454" className="text-green-700 font-semibold">+91 77806 13454</a> for a free inspection in Electronic City. We respond within 30 minutes and offer same-day installation.</p></div></div>} />;
}
